// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxgHNm1B9GDMdcU89HkoIiKk1Rj46p6HI',
    appId: '1:38007659451:web:ec48613235d506e0df829e',
    messagingSenderId: '38007659451',
    projectId: 'opocompit-dev',
    authDomain: 'opocompit-dev.firebaseapp.com',
    storageBucket: 'opocompit-dev.firebasestorage.app',
    measurementId: 'G-NPJ2HTQS9J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6MDUuq-H5zaHYXgEO25tLNS4Z7jDTe0I',
    appId: '1:38007659451:android:f50d7e67c483815bdf829e',
    messagingSenderId: '38007659451',
    projectId: 'opocompit-dev',
    storageBucket: 'opocompit-dev.firebasestorage.app',
  );
}
